#!/usr/bin/env node
/**
 * Extracts design tokens from the infinnity-frontend codebase into `tokens/`.
 *
 * Source of truth: src/components/App/style/themeMui5/variables.ts (the
 * `designTokens` object) plus packages/ui/src/theme/types.ts (the DesignTokens
 * contract). Nothing here is hand-authored: every value is read from that file,
 * so a re-run after a design-system release produces a reviewable diff.
 *
 * Usage:
 *   node scripts/sync/extract-tokens.mjs <path-to-infinnity-frontend>
 */

import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const frontend = process.argv[2];
if (!frontend) {
  console.error(
    'usage: node scripts/sync/extract-tokens.mjs <path-to-infinnity-frontend>'
  );
  process.exit(1);
}

const REPO = resolve(import.meta.dirname, '../..');
const VARIABLES = join(
  frontend,
  'src/components/App/style/themeMui5/variables.ts'
);
const OUT = join(REPO, 'tokens');

// ---------------------------------------------------------------------------
// Load `designTokens` out of the TypeScript source.
//
// variables.ts is a single object literal of string/number/array literals with
// no computed values, so stripping the import and the type annotation leaves
// valid ESM. If that ever stops being true this throws loudly rather than
// guessing — which is the intended behaviour.
// ---------------------------------------------------------------------------
const raw = await readFile(VARIABLES, 'utf8');
const body = raw
  .replace(/^import[^;]+;\s*/m, '')
  .replace(/export const designTokens: DesignTokens =/, 'export default');

if (!body.startsWith('export default')) {
  throw new Error(
    `${VARIABLES}: could not find "export const designTokens: DesignTokens =" — ` +
      'the token source moved or changed shape; update this script.'
  );
}
if (/\b(?:import|require|\$\{|=>)\b/.test(body)) {
  throw new Error(
    `${VARIABLES}: contains computed values; this extractor only handles literals.`
  );
}

const tmp = join(REPO, '.tokens-source.mjs');
await writeFile(tmp, body);
let tokens;
try {
  ({ default: tokens } = await import(pathToFileURL(tmp).href));
} finally {
  await rm(tmp, { force: true });
}

// ---------------------------------------------------------------------------
// Naming: --pliant-<kebab-path>. Deterministic, so diffs stay readable.
// ---------------------------------------------------------------------------
const kebab = (s) =>
  String(s)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();

const flatten = (node, path = []) => {
  const out = [];
  for (const [key, value] of Object.entries(node)) {
    const next = [...path, key];
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      out.push(...flatten(value, next));
    } else {
      out.push([next, value]);
    }
  }
  return out;
};

const cssVar = (path, prefix = 'pliant') =>
  `--${prefix}-${path.map(kebab).join('-')}`;

const cssValue = (value, path) => {
  const last = path.at(-1);
  if (typeof value === 'number') {
    // Radii are px in the source (MUI shape.borderRadius); weights are unitless.
    return /radius/i.test(last) ? `${value}px` : String(value);
  }
  return value;
};

const block = (title, source, entries) => {
  const width = Math.max(...entries.map(([name]) => name.length));
  const lines = entries
    .map(([name, value]) => `  ${name.padEnd(width)}: ${value};`)
    .join('\n');
  return `/* ${title}
 * Generated by scripts/sync/extract-tokens.mjs — do not edit by hand.
 * Source: ${source}
 */

:root {
${lines}
}
`;
};

const SOURCE = 'infinnity-frontend src/components/App/style/themeMui5/variables.ts';

const entriesFor = (keys, { prefix = 'pliant', skip = () => false } = {}) =>
  keys
    .filter((key) => tokens[key] !== undefined)
    .flatMap((key) =>
      flatten({ [key]: tokens[key] })
        .filter(([path]) => !skip(path))
        .map(([path, value]) => [cssVar(path, prefix), cssValue(value, path)])
    );

await mkdir(OUT, { recursive: true });

// --- colors -----------------------------------------------------------------
// `button` carries one non-colour leaf (shape.borderRadius) — it belongs in
// shape.css, so it is skipped here rather than duplicated.
const COLOR_GROUPS = [
  'primary',
  'secondary',
  'error',
  'warning',
  'info',
  'success',
  'neutral',
  'text',
  'background',
  'grey',
  'warmGrey',
  'basic',
  'pliantearth',
  'alert',
  'chip',
  'input',
  'tooltip',
  'navigation',
  'button',
];
await writeFile(
  join(OUT, 'colors.css'),
  block('Pliant colour tokens', SOURCE, [
    ...entriesFor(COLOR_GROUPS, {
      skip: (path) => path[0] === 'button' && path[1] === 'shape',
    }),
  ])
);

// --- typography -------------------------------------------------------------
// Two families of roles: MUI variants (`typography`) and component roles
// (`components`). Both are flattened under a single --pliant-type-* prefix.
const typeEntries = [
  ...flatten({ ...tokens.typography }).map(([path, value]) => [
    cssVar(['type', ...path]),
    cssValue(value, path),
  ]),
  ...flatten({ ...tokens.components }).map(([path, value]) => [
    cssVar(['type', ...path]),
    cssValue(value, path),
  ]),
];
await writeFile(
  join(OUT, 'typography.css'),
  block('Pliant typography tokens', SOURCE, typeEntries)
);

// --- shape ------------------------------------------------------------------
await writeFile(
  join(OUT, 'shape.css'),
  block('Pliant shape tokens', SOURCE, [
    [cssVar(['shape', 'border-radius']), cssValue(tokens.shape.borderRadius, ['radius'])],
    ...(tokens.tile
      ? [[cssVar(['tile', 'border-radius']), cssValue(tokens.tile.borderRadius, ['radius'])]]
      : []),
    [
      cssVar(['button', 'border-radius']),
      cssValue(tokens.button.shape.borderRadius, ['radius']),
    ],
  ])
);

// --- elevation --------------------------------------------------------------
// MUI's shadows array is index-addressed: elevation N is shadows[N].
await writeFile(
  join(OUT, 'elevation.css'),
  block(
    'Pliant elevation tokens',
    SOURCE,
    tokens.shadows.map((shadow, i) => [cssVar(['elevation', i]), shadow])
  )
);

// --- json mirror ------------------------------------------------------------
await writeFile(
  join(OUT, 'tokens.json'),
  `${JSON.stringify(
    {
      $comment:
        'Generated by scripts/sync/extract-tokens.mjs from infinnity-frontend. Do not edit by hand.',
      $source: SOURCE,
      designTokens: tokens,
    },
    null,
    2
  )}\n`
);

const count = (file) => file.split('\n').filter((l) => l.includes('--pliant-')).length;
const colors = await readFile(join(OUT, 'colors.css'), 'utf8');
console.log(
  `tokens/: ${count(colors)} colour, ${typeEntries.length} typography, ` +
    `3 shape, ${tokens.shadows.length} elevation custom properties written.`
);
